/*
 * Copyright 2022 maber01.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.ac.leedsbeckett.ltitoolset.resources;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.io.Serializable;
import java.util.UUID;


/**
 * A single String key that identifies resources based on the ID that
 * was generated by this API as a UUID. (Was created from ResourceKey)
 * 
 * @author jon
 */
public class ToolResourceKey implements Serializable
{
  String resourceId;
  /**
   * The standard constructor.
   * 
   * @param resourceId Annotated to help with serialization as JSON.
   */
  public ToolResourceKey( @JsonProperty("resourceId") String resourceId )
  {
    this.resourceId = resourceId;
  }

  /**
   * Get the resource ID that the platform generated for this resource.
   * 
   * @return The resource ID.
   */
  public String getResourceId()
  {
    return resourceId;
  }
  
  /**
   * Generate a new key as a UUID in standard string format.
   * @return A string version of the key.
   */
  public static ToolResourceKey generate()
  {
    return new ToolResourceKey( UUID.randomUUID().toString() );
  }
}
  
